
spring:
  application:
    name: spring-io-intro

  ai:
    watsonx:
      ai:
        base-url: $(WATSONX_BASE_URL)
        stream-endpoint: ${WATSONX_STREAM_ENDPOINT}
        text-endpoint: ${WATSONX_TEXT_ENDPOINT}
        embedding:
          enabled: true
      