
spring:
  application:
    name: spring-io-intro

  ai:
    watsonx:
      ai:
        base-url: https://us-south.ml.cloud.ibm.com
        embedding-endpoint: ml/v1/text/embeddings?version=2023-05-29
        text-endpoint: ml/v1/text/generation?version=2023-05-29
        i-a-m-token: ${WATSONX_IAM_TOKEN}
        embedding:
#          enabled: true
          options:
            model: ibm/granite-20b-multilingual
        project-id: ${WATSONX_PROJECT_ID}



springdoc:
  api-docs:
    path: /api-docs